const data = [
    {"name": "IIT Bombay"},
    {"name": "IIT Delhi"},
    {"name": "IIT Kanpur"},
    {"name": "IIT Kharagpur"},
    {"name": "IIT Madras"},
    {"name": "IIT Roorkee"},
    {"name": "IIT Guwahati"},
    {"name": "IIT Bhubaneswar"},
    {"name": "IIT Gandhinagar"},
    {"name": "IIT Hyderabad"},
    {"name": "IIT Jodhpur"},
    {"name": "IIT Patna"},
    {"name": "IIT Ropar"},
    {"name": "IIT Bhilai"},
    {"name": "IIT Goa"},
    {"name": "IIT Jammu"},
    {"name": "IIT Dhanbad (Indian School of Mines)"},
    {"name": "IIT Varanasi (Banaras Hindu University)"},
    {"name": "IIT Palakkad"},
    {"name": "IIT Tirupati"},
    {"name": "IIT Dharwad"},
    {"name": "IIT Mandi"},
    {"name": "IIT Indore"},
    {"name": "IIT (ISM) Dhanbad"},
    {"name": "IIT Ropar"},
    {"name": "IIT Bhubaneswar"},
    {"name": "IIT Gandhinagar"},
    {"name": "IIT Jodhpur"},
    {"name": "IIT Patna"},
    

    { "name": "NIT Tiruchirappalli" },
    { "name": "NIT Warangal" },
    { "name": "NIT Surathkal" },
    { "name": "NIT Calicut" },
    { "name": "NIT Rourkela" },
    { "name": "NIT Durgapur" },
    { "name": "NIT Kurukshetra" },
    { "name": "NIT Jaipur" },
    { "name": "NIT Silchar" },
    { "name": "NIT Allahabad" },
    { "name": "NIT Bhopal" },
    { "name": "NIT Hamirpur" },
    { "name": "NIT Jalandhar" },
    { "name": "NIT Agartala" },
    { "name": "NIT Raipur" },
    { "name": "NIT Patna" },
    { "name": "NIT Srinagar" },
    { "name": "NIT Surat" },
    { "name": "NIT Nagaland" },
    { "name": "NIT Arunachal Pradesh" },
    { "name": "NIT Manipur" },
    { "name": "NIT Mizoram" },
    { "name": "NIT Meghalaya" },
    { "name": "NIT Uttarakhand" },
    { "name": "NIT Goa" },
    { "name": "NIT Puducherry" },
    { "name": "NIT Delhi" },
    { "name": "NIT Andhra Pradesh" },
    { "name": "NIT Jharkhand" },
    { "name": "NIT Karnataka" },
    { "name": "NIT Maharashtra" },
    { "name": "NIT Sikkim" },
    { "name": "NIT West Bengal" },
    { "name": "NIT Tamil Nadu" },
    { "name": "NIT Himachal Pradesh" },

    { "name": "IIIT Bangalore" },
    { "name": "IIIT Hyderabad" },
    { "name": "IIIT Delhi" },
    { "name": "IIIT Allahabad" },
    { "name": "IIIT Bhubaneswar" },
    { "name": "IIIT Gwalior" },
    { "name": "IIIT Jabalpur" },
    { "name": "IIIT Kancheepuram" },
    { "name": "IIIT Lucknow" },
    { "name": "IIIT Kurnool" },
    { "name": "IIIT Dharwad" },
    { "name": "IIIT Kota" },
    { "name": "IIIT Manipur" },
    { "name": "IIIT Srirangam" },
    { "name": "IIIT Una" },
    { "name": "IIIT Vadodara" },
    { "name": "IIIT Gwalior " },

    { "name": "BITS Pilani" },
    { "name": "DTU (Delhi Technological University)" },
    { "name": "IISC Bangalore (Indian Institute of Science)" },
    { "name": "VIT Vellore (Vellore Institute of Technology)" },
    { "name": "Manipal Institute of Technology" },
    { "name": "Thapar Institute of Engineering and Technology" }
];

export default data;